version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: monday
    time: "09:00"
    timezone: "America/Buenos_Aires"
  versioning-strategy: auto
  commit-message:
    prefix: "chore: "
  allow:
    - dependency-name: "@dcl/*"
    - dependency-name: "@catalyst/*"
    - dependency-name: "@well-known-components/*"
    - dependency-name: "dcl-*"
  open-pull-requests-limit: 10
